# Generated by Django 3.1.8 on 2021-05-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=120)),
                ('is_Completed', models.BooleanField(default=False)),
                ('published_On', models.DateTimeField(verbose_name=False)),
            ],
        ),
    ]
